# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=5)),
                ('Player1score', models.IntegerField(default=0)),
                ('Player2score', models.IntegerField(default=0)),
                ('Player3score', models.IntegerField(default=0)),
                ('gameCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameCreator_user', to=settings.AUTH_USER_MODEL)),
                ('gameWinner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameWinner_user', to=settings.AUTH_USER_MODEL)),
                ('particapants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
