# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameWinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameWinner_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
