# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_mydict'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='GameStartStatus',
            field=models.IntegerField(default=0),
        ),
    ]
