# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_gamestartstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='currentTurn',
            field=models.IntegerField(default=0),
        ),
    ]
